spring:
  application:
    name: portfolio-service
  main:
    web-application-type: reactive
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  keyId: ${JWT_KEY_ID}
  secret: ${JWT_SECRET}

aws:
  region: ${AWS_REGION_NAME}
  s3:
    bucket: ${S3_BUCKET}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    resume-prefix: ${S3_RESUME_PREFIX}
    project-prefix: ${S3_PROJECT_PREFIX}
    profile-prefix: ${S3_PROFILE_PREFIX}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true
  group-configs:
    - group: public
      paths-to-match: 
        - /profile/**
        - /projects/**
        - /experiences/**
        - /skills/**
        - /contact/**
        - /resume/**
      display-name: Public API
    - group: admin
      paths-to-match:
        - /admin/**
        - /auth/**
      display-name: Admin API
