name: Deploy portfolio-service to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Debug secrets presence
        run: |
          echo "WIF_PROVIDER set? -> ${{ secrets.GCP_WIF_PROVIDER != '' }}"
          echo "SERVICE_ACCOUNT set? -> ${{ secrets.GCP_SERVICE_ACCOUNT != '' }}"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/portfolio-backend .

      - name: Push Docker image
        run: |
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/portfolio-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portfolio-service \
            --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/portfolio-backend \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated